const translations = {
    es: {
        heroTitle: "Experiencia inmersiva para todos",
        heroDesc: "La herramienta definitiva de Espejo VR para una experiencia visual única y envolvente.",
        txtStoreGoogle: "Google Play",
        txtStoreApple: "App Store",
        feat1Title: "Simetría Visual",
        feat1Desc: "Experimenta una nueva perspectiva visualizando tus movimientos en tiempo real.",
        feat2Title: "Instantáneo",
        feat2Desc: "Sin registros ni calibraciones complejas. Abrir y usar.",
        feat3Title: "Privado",
        feat3Desc: "Todo el procesamiento se realiza en tu dispositivo. Nada se sube a la nube.",
        supportTitle: "¿Necesitas Ayuda?",
        supportDesc: "Estamos aquí para escucharte. Si tienes problemas técnicos o sugerencias, contáctanos.",
        btnSupport: "Contactar Soporte",
        linkPrivacy: "Política de Privacidad",
        linkTerms: "Términos de Uso",
        txtCopyright: "© 2025 VR Mirror."
    },
    en: {
        heroTitle: "Immersive experience for everyone",
        heroDesc: "The ultimate VR Mirror tool for a unique and immersive visual experience.",
        txtStoreGoogle: "Google Play",
        txtStoreApple: "App Store",
        feat1Title: "Visual Symmetry",
        feat1Desc: "Experience a new perspective by visualizing your movements in real time.",
        feat2Title: "Instant",
        feat2Desc: "No signup or complex calibration. Just open and use.",
        feat3Title: "Private",
        feat3Desc: "All processing happens on your device. Nothing is uploaded to the cloud.",
        supportTitle: "Need Help?",
        supportDesc: "We are here to listen. If you have technical issues or suggestions, contact us.",
        btnSupport: "Contact Support",
        linkPrivacy: "Privacy Policy",
        linkTerms: "Terms of Service",
        txtCopyright: "© 2025 VR Mirror."
    },
    fr: {
        heroTitle: "Expérience immersive pour tous",
        heroDesc: "L'outil ultime de miroir VR pour une expérience visuelle unique.",
        txtStoreGoogle: "Google Play",
        txtStoreApple: "App Store",
        feat1Title: "Symétrie Visuelle",
        feat1Desc: "Découvrez une nouvelle perspective en visualisant vos mouvements en temps réel.",
        feat2Title: "Instantané",
        feat2Desc: "Pas d'inscription ni de calibrage complexe. Ouvrez et utilisez.",
        feat3Title: "Privé",
        feat3Desc: "Tout le traitement se fait sur votre appareil. Rien n'est envoyé sur le cloud.",
        supportTitle: "Besoin d'aide ?",
        supportDesc: "Nous sommes là pour vous écouter. Contactez-nous pour tout problème.",
        btnSupport: "Contacter le Support",
        linkPrivacy: "Politique de Confidentialité",
        linkTerms: "Conditions d'Utilisation",
        txtCopyright: "© 2025 VR Mirror."
    },
    de: {
        heroTitle: "Immersives Erlebnis für alle",
        heroDesc: "Das ultimative VR-Spiegel-Tool für ein einzigartiges visuelles Erlebnis.",
        txtStoreGoogle: "Google Play",
        txtStoreApple: "App Store",
        feat1Title: "Visuelle Symmetrie",
        feat1Desc: "Erleben Sie eine neue Perspektive durch Visualisierung Ihrer Bewegungen in Echtzeit.",
        feat2Title: "Sofortig",
        feat2Desc: "Keine Anmeldung oder komplexe Kalibrierung. Einfach öffnen und nutzen.",
        feat3Title: "Privat",
        feat3Desc: "Die gesamte Verarbeitung erfolgt auf Ihrem Gerät. Nichts wird in die Cloud hochgeladen.",
        supportTitle: "Brauchen Sie Hilfe?",
        supportDesc: "Wir sind hier, um zuzuhören. Kontaktieren Sie uns bei technischen Problemen.",
        btnSupport: "Support Kontaktieren",
        linkPrivacy: "Datenschutzrichtlinie",
        linkTerms: "Nutzungsbedingungen",
        txtCopyright: "© 2025 VR Mirror."
    },
    it: {
        heroTitle: "Esperienza immersiva per tutti",
        heroDesc: "Lo strumento definitivo per lo specchio VR per un'esperienza visiva unica.",
        txtStoreGoogle: "Google Play",
        txtStoreApple: "App Store",
        feat1Title: "Simmetria Visiva",
        feat1Desc: "Sperimenta una nuova prospettiva visualizzando i tuoi movimenti in tempo reale.",
        feat2Title: "Istantaneo",
        feat2Desc: "Nessuna registrazione o calibrazione complessa. Apri e usa.",
        feat3Title: "Privato",
        feat3Desc: "Tutta l'elaborazione avviene sul tuo dispositivo. Nulla viene caricato sul cloud.",
        supportTitle: "Hai bisogno di aiuto?",
        supportDesc: "Siamo qui per ascoltarti. Contattaci per problemi tecnici.",
        btnSupport: "Contatta il Supporto",
        linkPrivacy: "Informativa sulla Privacy",
        linkTerms: "Termini di Servizio",
        txtCopyright: "© 2025 VR Mirror."
    },
    pt: {
        heroTitle: "Experiência imersiva para todos",
        heroDesc: "A ferramenta definitiva de Espelho VR para uma experiência visual única.",
        txtStoreGoogle: "Google Play",
        txtStoreApple: "App Store",
        feat1Title: "Simetria Visual",
        feat1Desc: "Experimente uma nova perspectiva visualizando seus movimentos em tempo real.",
        feat2Title: "Instantâneo",
        feat2Desc: "Sem cadastro ou calibração complexa. Abra e use.",
        feat3Title: "Privado",
        feat3Desc: "Todo o processamento ocorre no seu dispositivo. Nada é enviado para a nuvem.",
        supportTitle: "Precisa de Ajuda?",
        supportDesc: "Estamos aqui para ouvir. Contacte-nos se tiver problemas técnicos.",
        btnSupport: "Contactar Suporte",
        linkPrivacy: "Política de Privacidade",
        linkTerms: "Termos de Serviço",
        txtCopyright: "© 2025 VR Mirror."
    },
    zh: {
        heroTitle: "给所有人的沉浸式体验",
        heroDesc: "独特的VR镜像视觉体验工具。",
        txtStoreGoogle: "Google Play",
        txtStoreApple: "App Store",
        feat1Title: "视觉对称",
        feat1Desc: "实时可视化您的动作，体验全新视角。",
        feat2Title: "即时可用",
        feat2Desc: "无需注册或复杂校准。打开即用。",
        feat3Title: "隐私保护",
        feat3Desc: "所有处理均在您的设备上进行。没有任何内容上传到云端。",
        supportTitle: "需要帮助？",
        supportDesc: "我们在这里倾听。如果您有技术问题或建议，请联系我们。",
        btnSupport: "联系支持",
        linkPrivacy: "隐私政策",
        linkTerms: "服务条款",
        txtCopyright: "© 2025 VR Mirror."
    },
    ja: {
        heroTitle: "すべての人のための没入体験",
        heroDesc: "ユニークな視覚体験のための究極のVRミラーツール。",
        txtStoreGoogle: "Google Play",
        txtStoreApple: "App Store",
        feat1Title: "視覚的な対称性",
        feat1Desc: "リアルタイムで動きを可視化し、新しい視点を体験してください。",
        feat2Title: "インスタント",
        feat2Desc: "登録や複雑なキャリブレーションは不要です。開いて使うだけ。",
        feat3Title: "プライバシー",
        feat3Desc: "すべての処理はデバイス上で行われます。クラウドには何もアップロードされません。",
        supportTitle: "ヘルプが必要ですか？",
        supportDesc: "技術的な問題や提案がある場合は、お問い合わせください。",
        btnSupport: "サポートに連絡",
        linkPrivacy: "プライバシーポリシー",
        linkTerms: "利用規約",
        txtCopyright: "© 2025 VR Mirror."
    },
    ko: {
        heroTitle: "모두를 위한 몰입형 경험",
        heroDesc: "독특한 시각적 경험을 위한 최고의 VR 미러 도구입니다.",
        txtStoreGoogle: "Google Play",
        txtStoreApple: "App Store",
        feat1Title: "시각적 대칭",
        feat1Desc: "실시간으로 움직임을 시각화하여 새로운 관점을 경험하세요.",
        feat2Title: "즉시 사용",
        feat2Desc: "가입이나 복잡한 보정이 필요 없습니다. 열고 바로 사용하세요.",
        feat3Title: "프라이버시",
        feat3Desc: "모든 처리는 기기에서 이루어집니다. 클라우드에 업로드되지 않습니다.",
        supportTitle: "도움이 필요하세요?",
        supportDesc: "기술적인 문제나 제안 사항이 있으면 문의해 주세요.",
        btnSupport: "지원팀에 문의",
        linkPrivacy: "개인정보 처리방침",
        linkTerms: "서비스 약관",
        txtCopyright: "© 2025 VR Mirror."
    },
    ru: {
        heroTitle: "Иммерсивный опыт для всех",
        heroDesc: "Лучший инструмент VR-зеркала для уникального визуального опыта.",
        txtStoreGoogle: "Google Play",
        txtStoreApple: "App Store",
        feat1Title: "Визуальная симметрия",
        feat1Desc: "Откройте новую перспективу, визуализируя свои движения в реальном времени.",
        feat2Title: "Мгновенно",
        feat2Desc: "Без регистрации и сложной калибровки. Просто откройте и используйте.",
        feat3Title: "Конфиденциально",
        feat3Desc: "Вся обработка происходит на вашем устройстве. Ничего не загружается в облако.",
        supportTitle: "Нужна помощь?",
        supportDesc: "Свяжитесь с нами, если у вас возникли технические проблемы.",
        btnSupport: "Связаться с поддержкой",
        linkPrivacy: "Политика конфиденциальности",
        linkTerms: "Условия использования",
        txtCopyright: "© 2025 VR Mirror."
    },
    ar: {
        heroTitle: "تجربة غامرة للجميع",
        heroDesc: "أداة مرآة الواقع الافتراضي لتجربة بصرية فريدة.",
        txtStoreGoogle: "Google Play",
        txtStoreApple: "App Store",
        feat1Title: "التناظر البصري",
        feat1Desc: "جرب منظوراً جديداً من خلال تصور حركاتك في الوقت الفعلي.",
        feat2Title: "فوري",
        feat2Desc: "لا تسجيل أو معايرة معقدة. فقط افتح واستخدم.",
        feat3Title: "خصوصية",
        feat3Desc: "تتم جميع المعالجات على جهازك. لا يتم تحميل أي شيء إلى السحابة.",
        supportTitle: "تحتاج للمساعدة؟",
        supportDesc: "نحن هنا للاستماع. اتصل بنا إذا كانت لديك مشاكل تقنية.",
        btnSupport: "اتصل بالدعم",
        linkPrivacy: "سياسة الخصوصية",
        linkTerms: "شروط الخدمة",
        txtCopyright: "© 2025 VR Mirror."
    },
    hi: {
        heroTitle: "सभी के लिए व्यापक अनुभव",
        heroDesc: "एक अद्वितीय दृश्य अनुभव के लिए अंतिम वीआर मिरर उपकरण।",
        txtStoreGoogle: "Google Play",
        txtStoreApple: "App Store",
        feat1Title: "दृश्य समरूपता",
        feat1Desc: "वास्तविक समय में अपनी गतिविधियों की कल्पना करके एक नए दृष्टिकोण का अनुभव करें।",
        feat2Title: "तत्काल",
        feat2Desc: "कोई साइनअप या जटिल अंशांकन नहीं। बस खोलें और उपयोग करें।",
        feat3Title: "निजी",
        feat3Desc: "सभी प्रसंस्करण आपके डिवाइस पर होता है। क्लाउड पर कुछ भी अपलोड नहीं किया जाता है।",
        supportTitle: "मदद की ज़रूरत है?",
        supportDesc: "यदि आपके पास तकनीकी समस्याएं या सुझाव हैं, तो हमसे संपर्क करें।",
        btnSupport: "समर्थन से संपर्क करें",
        linkPrivacy: "गोपनीयता नीति",
        linkTerms: "सेवा की शर्तें",
        txtCopyright: "© 2025 VR Mirror."
    },
    nl: {
        heroTitle: "Immersieve ervaring voor iedereen",
        heroDesc: "De ultieme VR Spiegel tool voor een unieke visuele ervaring.",
        txtStoreGoogle: "Google Play",
        txtStoreApple: "App Store",
        feat1Title: "Visuele Symmetrie",
        feat1Desc: "Ervaar een nieuw perspectief door uw bewegingen in real-time te visualiseren.",
        feat2Title: "Direct",
        feat2Desc: "Geen registratie of complexe kalibratie. Gewoon openen en gebruiken.",
        feat3Title: "Privé",
        feat3Desc: "Alle verwerking gebeurt op uw apparaat. Niets wordt geüpload naar de cloud.",
        supportTitle: "Hulp nodig?",
        supportDesc: "Neem contact met ons op als u technische problemen heeft.",
        btnSupport: "Neem contact op",
        linkPrivacy: "Privacybeleid",
        linkTerms: "Servicevoorwaarden",
        txtCopyright: "© 2025 VR Mirror."
    },
    sv: {
        heroTitle: "Inlevelsefull upplevelse för alla",
        heroDesc: "Det ultimata VR-spegelverktyget för en unik visuell upplevelse.",
        txtStoreGoogle: "Google Play",
        txtStoreApple: "App Store",
        feat1Title: "Visuell Symmetri",
        feat1Desc: "Upplev ett nytt perspektiv genom att visualisera dina rörelser i realtid.",
        feat2Title: "Omedelbar",
        feat2Desc: "Ingen registrering eller komplex kalibrering. Bara öppna och använd.",
        feat3Title: "Privat",
        feat3Desc: "All bearbetning sker på din enhet. Ingenting laddas upp till molnet.",
        supportTitle: "Behöver du hjälp?",
        supportDesc: "Kontakta oss om du har tekniska problem.",
        btnSupport: "Kontakta Support",
        linkPrivacy: "Integritetspolicy",
        linkTerms: "Användarvillkor",
        txtCopyright: "© 2025 VR Mirror."
    },
    da: {
        heroTitle: "Fordybende oplevelse for alle",
        heroDesc: "Det ultimative VR spejl værktøj til en unik visuel oplevelse.",
        txtStoreGoogle: "Google Play",
        txtStoreApple: "App Store",
        feat1Title: "Visuel Symmetri",
        feat1Desc: "Oplev et nyt perspektiv ved at visualisere dine bevægelser i realtid.",
        feat2Title: "Øjeblikkelig",
        feat2Desc: "Ingen tilmelding eller kompleks kalibrering. Bare åbn og brug.",
        feat3Title: "Privat",
        feat3Desc: "Al behandling sker på din enhed. Intet uploades til skyen.",
        supportTitle: "Brug for hjælp?",
        supportDesc: "Kontakt os, hvis du har tekniske problemer.",
        btnSupport: "Kontakt Support",
        linkPrivacy: "Privatlivspolitik",
        linkTerms: "Servicevilkår",
        txtCopyright: "© 2025 VR Mirror."
    },
    fi: {
        heroTitle: "Immersiivinen kokemus kaikille",
        heroDesc: "Lopullinen VR-peilityökalu ainutlaatuiseen visuaaliseen kokemukseen.",
        txtStoreGoogle: "Google Play",
        txtStoreApple: "App Store",
        feat1Title: "Visuaalinen symmetria",
        feat1Desc: "Koe uusi näkökulma visualisoimalla liikkeesi reaaliajassa.",
        feat2Title: "Välitön",
        feat2Desc: "Ei rekisteröitymistä tai monimutkaista kalibrointia. Avaa ja käytä.",
        feat3Title: "Yksityinen",
        feat3Desc: "Kaikki käsittely tapahtuu laitteellasi. Mitään ei ladata pilveen.",
        supportTitle: "Tarvitsetko apua?",
        supportDesc: "Ota meihin yhteyttä, jos sinulla on teknisiä ongelmia.",
        btnSupport: "Ota yhteyttä tukeen",
        linkPrivacy: "Tietosuojakäytäntö",
        linkTerms: "Käyttöehdot",
        txtCopyright: "© 2025 VR Mirror."
    },
    no: {
        heroTitle: "Oppslukende opplevelse for alle",
        heroDesc: "Det ultimate VR-speilverktyget for en unik visuell opplevelse.",
        txtStoreGoogle: "Google Play",
        txtStoreApple: "App Store",
        feat1Title: "Visuell Symmetri",
        feat1Desc: "Opplev et nytt perspektiv ved å visualisere bevegelsene dine i sanntid.",
        feat2Title: "Øyeblikkelig",
        feat2Desc: "Ingen registrering eller kompleks kalibrering. Bare åpne og bruk.",
        feat3Title: "Privat",
        feat3Desc: "All behandling skjer på enheten din. Ingenting lastes opp til skyen.",
        supportTitle: "Trenger du hjelp?",
        supportDesc: "Kontakt oss hvis du har tekniske problemer.",
        btnSupport: "Kontakt Support",
        linkPrivacy: "Personvernerklæring",
        linkTerms: "Vilkår for bruk",
        txtCopyright: "© 2025 VR Mirror."
    },
    tr: {
        heroTitle: "Herkes için sürükleyici deneyim",
        heroDesc: "Eşsiz bir görsel deneyim için nihai VR Ayna aracı.",
        txtStoreGoogle: "Google Play",
        txtStoreApple: "App Store",
        feat1Title: "Görsel Simetri",
        feat1Desc: "Hareketlerinizi gerçek zamanlı görselleştirerek yeni bir bakış açısı deneyimleyin.",
        feat2Title: "Anlık",
        feat2Desc: "Kayıt veya karmaşık kalibrasyon yok. Sadece açın ve kullanın.",
        feat3Title: "Gizli",
        feat3Desc: "Tüm işlemler cihazınızda gerçekleşir. Buluta hiçbir şey yüklenmez.",
        supportTitle: "Yardıma mı ihtiyacınız var?",
        supportDesc: "Teknik sorunlarınız varsa bizimle iletişime geçin.",
        btnSupport: "Destek ile İletişime Geçin",
        linkPrivacy: "Gizlilik Politikası",
        linkTerms: "Hizmet Şartları",
        txtCopyright: "© 2025 VR Mirror."
    },
    pl: {
        heroTitle: "Wciągające doświadczenie dla każdego",
        heroDesc: "Najlepsze narzędzie lustrzane VR zapewniające wyjątkowe wrażenia wizualne.",
        txtStoreGoogle: "Google Play",
        txtStoreApple: "App Store",
        feat1Title: "Symetria wizualna",
        feat1Desc: "Odkryj nową perspektywę, wizualizując swoje ruchy w czasie rzeczywistym.",
        feat2Title: "Natychmiastowe",
        feat2Desc: "Bez rejestracji i skomplikowanej kalibracji. Po prostu otwórz i używaj.",
        feat3Title: "Prywatne",
        feat3Desc: "Całe przetwarzanie odbywa się na urządzeniu. Nic nie jest wysyłane do chmury.",
        supportTitle: "Potrzebujesz pomocy?",
        supportDesc: "Skontaktuj się z nami w przypadku problemów technicznych.",
        btnSupport: "Skontaktuj się z pomocą",
        linkPrivacy: "Polityka prywatności",
        linkTerms: "Warunki korzystania",
        txtCopyright: "© 2025 VR Mirror."
    },
    vi: {
        heroTitle: "Trải nghiệm đắm chìm cho mọi người",
        heroDesc: "Công cụ Gương VR tối ưu cho trải nghiệm hình ảnh độc đáo.",
        txtStoreGoogle: "Google Play",
        txtStoreApple: "App Store",
        feat1Title: "Đối xứng thị giác",
        feat1Desc: "Trải nghiệm một góc nhìn mới bằng cách hình dung chuyển động của bạn trong thời gian thực.",
        feat2Title: "Tức thì",
        feat2Desc: "Không cần đăng ký hoặc hiệu chỉnh phức tạp. Chỉ cần mở và sử dụng.",
        feat3Title: "Riêng tư",
        feat3Desc: "Tất cả quá trình xử lý diễn ra trên thiết bị của bạn. Không có gì được tải lên đám mây.",
        supportTitle: "Cần giúp đỡ?",
        supportDesc: "Liên hệ với chúng tôi nếu bạn gặp vấn đề kỹ thuật.",
        btnSupport: "Liên hệ Hỗ trợ",
        linkPrivacy: "Chính sách Bảo mật",
        linkTerms: "Điều khoản Dịch vụ",
        txtCopyright: "© 2025 VR Mirror."
    }
};

function changeLanguage() {
    const lang = document.getElementById('languageSelector').value;
    const texts = translations[lang] || translations['en'];

    const elements = [
        'heroTitle', 'heroDesc',
        'txtStoreGoogle', 'txtStoreApple',
        'feat1Title', 'feat1Desc',
        'feat2Title', 'feat2Desc',
        'feat3Title', 'feat3Desc',
        'supportTitle', 'supportDesc', 'btnSupport',
        'linkPrivacy', 'linkTerms', 'txtCopyright'
    ];

    elements.forEach(id => {
        const el = document.getElementById(id);
        if (el && texts[id]) {
            el.innerText = texts[id];
        }
    });
}

// --- 3D Tilt Effect Removed ---
// Cards remain static floating elements as requested.
